### ISSUE TITLE
Add .IfNullOrWhiteSpace() .IfNullOrEmpty() for string properties

### ISSUE THREAD

**Issue by mantinband** [mantinband/throw#10]
Currently, if we have an object with a nullable string property

```csharp
record Person(string? Name);
```

We need 2 checks to do this:

```csharp
person.Throw()
    .IfNull(p => p.Name)
    .IfEmpty(p => p.Name!);
```

Instead, this would be more fluent and performant:

```csharp
person.Throw()
    .IfNullOrEmpty(p => p.Name);
```
```csharp
person.Throw()
    .IfNullOrWhiteSpace(p => p.Name);
```

**Comment by m-jovanovic** [comment]
I would love to tackle this issue. I'll start working on it later, hope to have a PR ready within a day. 🚀
