### ISSUE TITLE
Add string .IfEndsWith .IfNotEndsWith

### ISSUE THREAD

**Issue by mantinband** [mantinband/throw#22]
Add validation on whether a string ends or doesn't end with a given suffix. For example:

```csharp
string name = "John"

name.Throw().IfEndsWith("hn");
name.Throw().IfNotEndsWith("123");
```

Also, add the corresponding extension methods for string properties. For example:

```csharp
var person = new { Name = "John" };

person.Throw().IfEndsWith(p => p.Name, "Jo");
person.Throw().IfNotEndsWith(p => p.Name, "Jo");
```

**Comment by dwakel** [comment]
I will pick this task up

**Comment by dwakel** [comment]
I've raised a PR for this @mantinband
