### ISSUE TITLE
Add option to pass `StringComparison` to string .IfEquals

### ISSUE THREAD

**Issue by mantinband** [mantinband/throw#24]
Currently, we have the following capabilities:

```csharp
"foo".Throw()
    .IfEquals("foo") // string.Equals("foo", "foo", StringComparison.Ordinal)
    .IfEqualsIngoreCase("FOO"); // string.Equals("foo", "foo", StringComparison.OrdinalIgnoreCase)
```
An overload that can be useful, is passing any of the `StringComparison` enum values.

The current string `.IfEquals` extension method can be modified to include `StringComparison comparisonType = StringComparison.Ordinal)`

Things to notice:
1. The `Validator.Strings.cs` class has separate equals/not equals methods for the different casings. This can be merged to a single `ThrowIfEquals` and `ThrowIfNotEquals` that receives a `StringComparison` comparison type. The exception message can then be updated to something like 
`String should not be equal to {otherString} (comparison type: {comparisonType}).`
2. We should make sure we unit test the various scenarios

**Comment by abhijithsundr** [comment]
I can take this up. Let me know.

**Comment by abhijithsundr** [comment]
Hi, I'm new here and I'd like to contribute. 

Please take a look at the PR i've made and let me know what I need to do next.

**Comment by mantinband** [comment]
Thanks again @abhijithsundr for your contribution 🙌🏽
