### ISSUE TITLE
Add collection `.IfContains` and `IfNotContains`

### ISSUE THREAD

**Issue by mantinband** [mantinband/throw#39]
Add the following extension methods for collections:

```csharp
var collection = new[] { "one", "two", "three" };

collection.Throw().IfCotnains("one");
collection.Throw().IfNotContains("four");
```

And the corresponding methods for collection properties

```csharp
var foo = new { Numbers = new[] { "one", "two", "three" } };

foo.Throw().IfCotnains(f => f.Numbers, "one");
foo.Throw().IfNotContains(f => f.Numbers, "four");
```

**Comment by mehdihadeli** [comment]
@mantinband Great Work.
I will pick this issue for developing.

**Comment by mantinband** [comment]
Awesome 🔥🔥 let me know if you have any questions 🤙🏼

**Comment by mehdihadeli** [comment]
@mantinband Sure, Thanks

**Comment by mehdihadeli** [comment]
I added them here #43

**Comment by AndreasHoersken** [comment]
Can this issue be closed? Changes seem to be integrated in main-branch.

**Comment by mehdihadeli** [comment]
@mantinband  I added `IfContains` and `IfNoContains` collection properties in this pull request
#44
