### ISSUE TITLE
Remove dependency on JetBrains.Annotations

### ISSUE THREAD

**Issue by TechInterMezzo** [mantinband/throw#50]
Would it be possible to remove the dependency on JetBrains.Annotations?
To avoid a dependency hell as much as possible I like to have a minimum of dependencies for every nuget package I use.
Since the new .NET versions have a very good support for nullable reference types I am not really sure if there is a need for those null annotations.

**Comment by mantinband** [comment]
Yeah, I think that shouldn't be a problem. I'll remove it.
