### ISSUE TITLE
Add string .IfMatches(regex) 

### ISSUE THREAD

**Issue by mantinband** [mantinband/throw#8]
Add throwing an exception if the string matches a given regex

Something like this:

1. Using string as input
```csharp
"My string".Throw().IfMatches("My.*ing$")
```

2. Using regex as input
```csharp
"My string".Throw().IfMatches(new Regex("My.*ing$"))
```

and the corresponding extension methods for properties
```csharp
user.Throw()IfMatches(user => user.Honorific, "^Dr")
``` 

```csharp
user.Throw()IfMatches(user => user.Honorific, "^Dr")
```

**Comment by JeremyEspresso** [comment]
I would like to pick up this issue if possible.
If that's okay, @mantinband, would you want these to be added to the `Validator.Strings.cs` or would you prefer a separate `Validator.Regex.cs` file for these.

**Comment by mantinband** [comment]
You can go ahead and add it to the *.Strings.cs, I have plans for a small refactor in the future 🤙🏼

**Comment by mantinband** [comment]
Thanks! 🔥

**Comment by JeremyEspresso** [comment]
@mantinband Do we want to add `IfNotMatches` versions as well?

**Comment by mantinband** [comment]
Yup, you’re welcome to implement it as part of this or future PR
