### ISSUE TITLE
Add string .IfLengthEquals(length) .IfLengthNotEquals(length)

### ISSUE THREAD

**Issue by mantinband** [mantinband/throw#9]
Add throwing an exception if the string length equals/doesn't equal the given length

Something like this:

Equals:
```csharp
"str".Throw().IfLengthEquals(3)
```

Not Equals:
```csharp
"str".Throw().IfLengthNotEquals(3)
```

and the corresponding extension methods for properties
```csharp
user.Throw().IfLengthEquals(user => user.Name, 3)
``` 
```csharp
user.Throw().IfLengthNotEquals(user => user.Name, 3)
```

**Comment by DevJonie** [comment]
Hi @mantinband, I'm new to oss.
I've worked on this issue, all tests passed.
Can I go ahead and create a PR?

**Comment by mantinband** [comment]
Hey @DevJonie! Yes, you can go ahead and create a PR. Can you please also add tests to validate your logic? Thanks for joining me on this project 🙏🏼😎
